return {
    ---@param cutscene WorldCutscene
    patient0034 = function(cutscene) 
        local y = os.time() - 86400
        local formatted_date = os.date("%m/%d/%Y", y)
        cutscene:text("* [voice:sign]\"Patient 0034 -[wait:2] Entered the hospital at " .. formatted_date .. ".\"")
        cutscene:text("* [voice:sign]\"Condition - Influenza.\"")
        cutscene:text("* [voice:sign]\"Don't give constant care,[wait:2] occasional check ups.\"[wait:3] \n* \"Provide mediocre food.\"")
        end, 
    
    snake_encounter = function(cutscene)  
        local kris = cutscene:getCharacter("kris")
        local ralsei = cutscene:getCharacter("ralsei")
        cutscene:detachFollowers()
        local wx, wy = cutscene:getMarker("walk_here")
        local snake_1 = cutscene:spawnNPC("snake", 3180, 380)
        local snake_2 = cutscene:spawnNPC("snake", 3090, 453)
        local snake_3 = cutscene:spawnNPC("snake", 3180, 530)
        snake_1.reflections = true 
        snake_2.reflections = true 
        snake_3.reflections = true 
        Game.world.timer:tween(2.5, Game.fader, {alpha = 0.5})
        kris:walkTo(wx, wy, 2.5)
        ralsei:walkTo(wx - 50, wy, 2.5)
        cutscene:wait(3)
        local function stext(txt, x, y)
            local txt = DialogueText("[voice:none][wave:1]"..txt.."", x or 240, y or 95)
            Game.stage:addChild(txt)
            cutscene:wait(function() return not txt:isTyping() end)
            txt:fadeOutAndRemove(0.5)
            cutscene:wait(0.5)
        end 
        stext("Hisssssss...")
        stext("Who daressss come here?", 115)
        cutscene:text("* (Kris,[wait:3] let's be careful...)", "surprise_neutral_side", "ralsei")
        cutscene:detachCamera()
        kris:walkTo(kris.x + 200, kris.y, 2.5)
        ralsei:walkTo(ralsei.x + 200, ralsei.y, 2.5)
        cutscene:panTo(Game.world.camera.x + 400, Game.world.camera.y, 2.5, "in-quart")
        cutscene:wait(3)
        ralsei:setAnimation("laugh")
        cutscene:setTextboxTop(true)
        cutscene:text("* You guys look so cute!", "blush_pleased_open", "ralsei")
        Game.fader.alpha = 0 
        Assets.playSound("locker")
        Game.world.music:play("silly")
        cutscene:wait(0.5)
        cutscene:text("* H-Hey! We're...[wait:3] more than that!")
        cutscene:text("* Yeah! We're sick of everyone toying around with us!")
        cutscene:text("* Hey,[wait:3] shut up you two.[wait:5]\n* Only I can do the talking.")
        ralsei:resetSprite()
        ralsei:shake(2)
        ralsei:setFacing("right")
        cutscene:wait(cutscene:playSound("wing"))
        cutscene:text("* S[wait:2]-Sorry boss..")
        cutscene:text("* Anyway,[wait:3] I take it you two\ndon't have manners?")
        Assets.playSound("wing")
        ralsei:setSprite("battle/hurt_1")
        cutscene:text("* Hey! We have manners,[wait:3] more than you do!", "angrier", "ralsei")
        cutscene:text("* Don't you even try to insult me,[wait:3] goatboy!")
        ralsei:resetSprite()
        ralsei:shake(2)
        ralsei:setFacing("right")
        cutscene:wait(cutscene:playSound("wing"))
        cutscene:text("* I'll compliment you instead then!", "owo", "ralsei")
        Game.world.music:fade(0, 0.5)
        cutscene:wait(0.5)
        cutscene:text("* Umm...", "surprise_neutral_side", "ralsei")
        cutscene:text("* I...[wait:4] uh...[wait:4] like your bravado?", "surprise_neutral", "ralsei")
        cutscene:wait(0.5)
        cutscene:text("* Hey! This is a real tough outer shell!")
        cutscene:text("* Let's get em,[wait:2] boys!")
        cutscene:startEncounter("snakes", nil, {{"snake", snake_1}, {"snake", snake_2}, {"snake", snake_3}})
    end

}